### ISSUE TITLE
Probably being a super huge noob but....

### ISSUE THREAD

**Issue by rocketlogger1** [Gadorach/SD2VITA#1]
....I sent the zipped up gerber files to allpcb for manufacturing and they message back saying the np drill file is missing.  I see a file for adapter_pth_drill.gbr but is this for something else?  I tried reading up on gerber files but it's all greek to me.  Can you tell me if the np drill file is the file above, and if not is one needed?  Sorry for the noobish questions, I'd love to have your design printed.

**Comment by Gadorach** [comment]
All VIAs are plated, therefore there are no non-plated drill holes, and consequently no np_drill files. The board house is just not actually checking the design properly otherwise they'd know that.
